openapi: 3.0.0
servers:
  - url: >-
      https://mocksvc.mulesoft.com/mocks/21d01ac7-3cd8-4348-b8d0-2dc61f05bb92/api
info:
  version: 2.0.0
  title: American Flights API
paths:
  /flights:
    get:
      operationId: GET_flights
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flights'
              example:
                - id: 1
                  code: ER38sd
                  price: 400
                  departureDate: 2016/03/20
                  origin: MUA
                  destination: SFO
                  emptySeats: 2
                  plane:
                    type: Boeing 737
                    totalSeats: 150
                - id: 2
                  code: ER45if
                  price: 345.99
                  departureDate: 2016/02/11
                  origin: MUA
                  destination: LAX
                  emptySeats: 52
                  plane:
                    type: Boeing 777
                    totalSeats: 300
      parameters:
        - in: query
          name: destination
          required: true
          schema:
            type: string
            enum:
              - SFO
              - LAX
              - CLE
    post:
      operationId: POST_flights
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Flight added (but not really)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Flight'
            example:
              code: ER38sd
              price: 400
              departureDate: 2016/03/20
              origin: MUA
              destination: SFO
              emptySeats: 2
              plane:
                type: Boeing 737
                totalSeats: 150
        required: true
  '/flights/{ID}':
    get:
      operationId: GET_flights-ID
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
              example:
                id: 1
                code: ER38sd
                price: 400
                departureDate: 2016/03/20
                origin: MUA
                destination: SFO
                emptySeats: 2
                plane:
                  type: Boeing 737
                  totalSeats: 150
    delete:
      operationId: DELETE_flights-ID
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Flight deleted (but not really)
    put:
      operationId: PUT_flights-ID
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  message: Flight updated (but not really)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Flight'
            example:
              code: ER38sd
              price: 400
              departureDate: 2016/03/20
              origin: MUA
              destination: SFO
              emptySeats: 2
              plane:
                type: Boeing 737
                totalSeats: 150
        required: true
    parameters:
      - in: path
        name: ID
        required: true
        schema:
          type: string
components:
  schemas:
    Flight:
      type: object
      example:
        id: 1
        code: ER38sd
        price: 400
        departureDate: 2016/03/20
        origin: MUA
        destination: SFO
        emptySeats: 2
        plane:
          type: Boeing 737
          totalSeats: 150
      properties:
        id:
          type: integer
        code:
          type: string
        price:
          type: number
        departureDate:
          type: string
        origin:
          type: string
        destination:
          type: string
        emptySeats:
          type: integer
        plane:
          properties:
            type:
              type: string
            totalSeats:
              type: integer
          type: object
          required:
            - type
            - totalSeats
      required:
        - code
        - price
        - departureDate
        - origin
        - destination
        - emptySeats
    Flights:
      type: array
      example:
        - id: 1
          code: ER38sd
          price: 400
          departureDate: 2016/03/20
          origin: MUA
          destination: SFO
          emptySeats: 2
          plane:
            type: Boeing 737
            totalSeats: 150
        - id: 2
          code: ER45if
          price: 345.99
          departureDate: 2016/02/11
          origin: MUA
          destination: LAX
          emptySeats: 52
          plane:
            type: Boeing 777
            totalSeats: 300
      items:
        $ref: '#/components/schemas/Flight'
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  securitySchemes: {}
  headers: {}
  callbacks: {}
  links: {}
