swagger: '2.0'
info:
  version: '2.0.0'
  title: American Flights API
host: mocksvc.mulesoft.com
basePath: /mocks/21d01ac7-3cd8-4348-b8d0-2dc61f05bb92/api
schemes:
  - https
paths:
  /flights:
    get:
      operationId: GET_flights
      produces:
        - application/json
      responses:
        '200':
          description: ''
          examples:
            application/json:
              - id: 1
                code: ER38sd
                price: 400
                departureDate: 2016/03/20
                origin: MUA
                destination: SFO
                emptySeats: 2
                plane:
                  type: Boeing 737
                  totalSeats: 150
              - id: 2
                code: ER45if
                price: 345.99
                departureDate: 2016/02/11
                origin: MUA
                destination: LAX
                emptySeats: 52
                plane:
                  type: Boeing 777
                  totalSeats: 300
          schema:
            $ref: '#/definitions/Flights'
      parameters:
        - enum:
            - SFO
            - LAX
            - CLE
          in: query
          name: destination
          required: true
          type: string
    post:
      operationId: POST_flights
      produces:
        - application/json
      responses:
        '201':
          description: ''
          schema:
            example:
              message: Flight added (but not really)
      consumes:
        - application/json
      parameters:
        - schema:
            $ref: '#/definitions/Flight'
            example:
              code: ER38sd
              price: 400
              departureDate: 2016/03/20
              origin: MUA
              destination: SFO
              emptySeats: 2
              plane:
                type: Boeing 737
                totalSeats: 150
          in: body
          name: body
          required: true
  '/flights/{ID}':
    get:
      operationId: GET_flights-ID
      produces:
        - application/json
      responses:
        '200':
          description: ''
          examples:
            application/json:
              id: 1
              code: ER38sd
              price: 400
              departureDate: 2016/03/20
              origin: MUA
              destination: SFO
              emptySeats: 2
              plane:
                type: Boeing 737
                totalSeats: 150
          schema:
            $ref: '#/definitions/Flight'
    delete:
      operationId: DELETE_flights-ID
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            example:
              message: Flight deleted (but not really)
    put:
      operationId: PUT_flights-ID
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            example:
              message: Flight updated (but not really)
      consumes:
        - application/json
      parameters:
        - schema:
            $ref: '#/definitions/Flight'
            example:
              code: ER38sd
              price: 400
              departureDate: 2016/03/20
              origin: MUA
              destination: SFO
              emptySeats: 2
              plane:
                type: Boeing 737
                totalSeats: 150
          in: body
          name: body
          required: true
    parameters:
      - in: path
        name: ID
        required: true
        type: string
definitions:
  Flight:
    type: object
    example:
      id: 1
      code: ER38sd
      price: 400
      departureDate: 2016/03/20
      origin: MUA
      destination: SFO
      emptySeats: 2
      plane:
        type: Boeing 737
        totalSeats: 150
    properties:
      id:
        type: integer
      code:
        type: string
      price:
        type: number
      departureDate:
        type: string
      origin:
        type: string
      destination:
        type: string
      emptySeats:
        type: integer
      plane:
        properties:
          type:
            type: string
          totalSeats:
            type: integer
        type: object
        required:
          - type
          - totalSeats
    required:
      - code
      - price
      - departureDate
      - origin
      - destination
      - emptySeats
  Flights:
    type: array
    example:
      - id: 1
        code: ER38sd
        price: 400
        departureDate: 2016/03/20
        origin: MUA
        destination: SFO
        emptySeats: 2
        plane:
          type: Boeing 737
          totalSeats: 150
      - id: 2
        code: ER45if
        price: 345.99
        departureDate: 2016/02/11
        origin: MUA
        destination: LAX
        emptySeats: 52
        plane:
          type: Boeing 777
          totalSeats: 300
    items:
      $ref: '#/definitions/Flight'